screen = <profile> vertexSnapping dithering lessColors resolution

profile.DEFAULT = vertexSnapping dithering lessColors resolution:0.2
profile.JUST_PIXELS = !vertexSnapping !dithering !lessColors resolution:0.2
profile.NOTHING = !vertexSnapping !dithering !lessColors resolution:1.0

sliders = resolution